### ISSUE TITLE
Using sortDirection = 'asc', the data is still sorted descending.

### ISSUE THREAD

**Issue by sulha199** [chrisvxd/combine-pagination#14]
Hi @chrisvxd

**Issue:**
Using sortDirection = 'asc', the data is still sorted descending.

**Solution:**
Add asc sorting on _sortPage()

PR: https://github.com/chrisvxd/combine-pagination/pull/13

**Comment by sulha199** [comment]
https://github.com/chrisvxd/combine-pagination/pull/13

**Comment by chrisvxd** [comment]
Closed by #13, regression test in #15
